# Generated by Django 3.2.13 on 2022-04-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cathedral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('slide', models.ImageField(default='/banners/slide-5.jpg', upload_to='banners/')),
            ],
        ),
    ]
