# Generated by Django 3.2.13 on 2022-04-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cathedral', '0003_adbannerone_adbannertwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWelcomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/banners/parish.jpg', upload_to='banners/')),
            ],
        ),
    ]
