# Generated by Django 3.2.13 on 2022-04-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cathedral', '0004_homewelcomeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbannerone',
            name='link',
            field=models.URLField(default='https://parishbits.com'),
        ),
        migrations.AddField(
            model_name='adbannertwo',
            name='link',
            field=models.URLField(default='https://parishbits.com'),
        ),
    ]
