# Generated by Django 3.2.11 on 2022-01-24 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=41)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=250)),
                ('announcer', models.CharField(max_length=250)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Sacrament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=41)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=41)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parishioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('id_number', models.CharField(max_length=250, unique=True)),
                ('registration_date', models.DateField()),
                ('display_pic', models.ImageField(blank=True, default='/banners/user.png', null=True, upload_to='banners/')),
                ('slug', models.SlugField(max_length=31, unique=True)),
                ('community', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parishoners', to='stkevins.community')),
                ('sacraments', models.ManyToManyField(blank=True, related_name='parishoners', to='stkevins.Sacrament')),
                ('societies', models.ManyToManyField(blank=True, related_name='parishoners', to='stkevins.Society')),
            ],
        ),
        migrations.CreateModel(
            name='Levy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=41)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=31, unique=True)),
                ('parishioner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='levies', to='stkevins.parishioner')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=41)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=31, unique=True)),
                ('parishioner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='stkevins.parishioner')),
            ],
        ),
    ]
