# Generated by Django 3.2.11 on 2022-01-27 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stkevins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='levy',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
