# Generated by Django 3.2.11 on 2022-01-28 12:48

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('stkevins', '0002_auto_20220127_1123'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
