# Generated by Django 3.2.11 on 2022-01-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stkevins', '0003_auto_20220128_1248'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
            ],
        ),
    ]
