# Generated by Django 3.2.13 on 2022-04-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stkevins', '0005_auto_20220302_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ImageField(default='/banners/img1.jpg', upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/banners/home_bg.jpg', upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='ParishPriest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/banners/frjim2.jpeg', upload_to='banners/')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
